# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机IP')),
                ('private_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='other IP')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口号')),
                ('username', models.CharField(blank=True, max_length=16, null=True, verbose_name='管理用户名')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('use_default_auth', models.BooleanField(default=True, verbose_name='使用默认管理账号')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC地址')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=128, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='硬盘')),
                ('system_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型')),
                ('system_version', models.CharField(blank=True, max_length=8, null=True, verbose_name='系统版本号')),
                ('status', models.IntegerField(blank=True, choices=[(1, '已使用'), (2, '未使用'), (3, '报废')], default=1, null=True, verbose_name='机器状态')),
                ('env', models.IntegerField(blank=True, choices=[(1, '生产环境'), (2, '测试环境'), (3, 'autoscaling')], null=True, verbose_name='运行环境')),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
