# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetalias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ManyToManyField(blank=True, to='asset.AssetGroup', verbose_name='所属主机组'),
        ),
    ]
