# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170629_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetalias',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetalias',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='group',
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, default=1, max_length=50, null=True, verbose_name='机器状态'),
        ),
        migrations.DeleteModel(
            name='AssetAlias',
        ),
        migrations.DeleteModel(
            name='AssetGroup',
        ),
    ]
