# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170629_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='group',
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asset.AssetGroup', verbose_name='所属主机组'),
        ),
    ]
