# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20170712_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='instance',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='实例ID'),
        ),
        migrations.AddField(
            model_name='asset',
            name='instance_status',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='实例状态'),
        ),
        migrations.AddField(
            model_name='asset',
            name='instance_type',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='实例类型'),
        ),
        migrations.AddField(
            model_name='asset',
            name='security_group',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='安全组'),
        ),
    ]
