# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20170713_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='instance_status',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='实例状态'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='instance_type',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='实例类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='security_group',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='安全组'),
        ),
    ]
